# -*- conf -*-

font=IosevkaTerm:size=12,TwitterColorEmoji:size=12,monospace:size=12

[mouse]
hide-when-typing=yes

[key-bindings]
color-theme-toggle=Control+t

[colors-light]
alpha=1.0
alpha-mode=default # Can be `default`, `matching` or `all`
background=eeeeee
# copied from https://codeberg.org/dnkl/foot/src/branch/master/themes/paper-color
cursor=eeeeee 444444
background=eeeeee
foreground=000000
regular0=eeeeee  # black
regular1=af0000  # red
regular2=008700  # green
regular3=5f8700  # yellow
regular4=0087af  # blue
regular5=878787  # magenta
regular6=005f87  # cyan
regular7=764e37  # white
bright0=bcbcbc   # bright black
bright1=d70000   # bright red
bright2=d70087   # bright green
bright3=8700af   # bright yellow
bright4=d75f00   # bright blue
bright5=d75f00   # bright magenta
bright6=4c7a5d   # bright cyan
bright7=005faf   # bright white

[bell]
system=yes
urgent=yes
notify=yes
visual=yes

